-- CreateTable
CREATE TABLE "invoice_templates" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'Default',
    "isDefault" BOOLEAN NOT NULL DEFAULT true,
    "logoPosition" TEXT NOT NULL DEFAULT 'left',
    "showClinicName" BOOLEAN NOT NULL DEFAULT true,
    "showAddress" BOOLEAN NOT NULL DEFAULT true,
    "showContact" BOOLEAN NOT NULL DEFAULT true,
    "templateStyle" TEXT NOT NULL DEFAULT 'classic',
    "itemTableStyle" TEXT NOT NULL DEFAULT 'bordered',
    "totalsPosition" TEXT NOT NULL DEFAULT 'right',
    "paymentTerms" TEXT,
    "showDueDate" BOOLEAN NOT NULL DEFAULT true,
    "showPaymentMethods" BOOLEAN NOT NULL DEFAULT true,
    "lateFeeEnabled" BOOLEAN NOT NULL DEFAULT false,
    "lateFeePercent" DOUBLE PRECISION DEFAULT 0,
    "lateFeeDays" INTEGER DEFAULT 30,
    "taxLabel" TEXT NOT NULL DEFAULT 'Tax',
    "taxType" TEXT NOT NULL DEFAULT 'percentage',
    "showTaxBreakdown" BOOLEAN NOT NULL DEFAULT false,
    "taxId" TEXT,
    "footerText" TEXT,
    "showSignature" BOOLEAN NOT NULL DEFAULT false,
    "signatureLabel" TEXT DEFAULT 'Authorized Signature',
    "primaryColor" TEXT NOT NULL DEFAULT '#0891b2',
    "headerBgColor" TEXT,
    "footerBgColor" TEXT,
    "fontFamily" TEXT NOT NULL DEFAULT 'Arial, sans-serif',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "invoice_templates_pkey" PRIMARY KEY ("id")
);
